name: Main tests

on: [push, pull_request]

jobs:
  macOS:
    strategy:
      matrix:
        version: [14]
      fail-fast: false
    runs-on: macos-${{ matrix.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Install Brew dependencies
      run: |
        brew update
        brew bundle --verbose
        cat /etc/paths.d/TeX >> $GITHUB_PATH
    - name: Set up virtual environment
      run: |
        python3 -m venv --system-site-packages $GITHUB_WORKSPACE/myVenv
        echo "$GITHUB_WORKSPACE/myVenv/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/myVenv" >> $GITHUB_ENV
    - name: Configure
      run: |
        echo "PATH: $PATH"
        echo "VIRTUAL_ENV: $VIRTUAL_ENV"
        mkdir build
        cd build
        cmake ../ -DBUILD_TESTING=yes
    - name: Build
      run: cd build && make -j 4
    - name: Install
      run: cd build && sudo make install
    - name: Build tests
      run: cd build && make tests -j 4
    - name: Run tests
      run: cd build && ctest --verbose
